Parameters:
  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Environment Size (S,M,L)
  DatabaseName:
    Type: String
    Default: wordpress
  DatabaseUser:
    Type: String
    Default: wordpress
  DatabasePassword:
    Type: String
    Default: w0rdpr355
    NoEcho: true
Mappings:
  RegionMap:
    us-east-1:
      AMALINUX: ami-02354e95b39ca8dec
    us-east-2:
      AMALINUX: ami-07c8bc5c1ce9598c3
    us-west-1:
      AMALINUX: ami-0ec6517f6edbf8044
    us-west-2:
      AMALINUX: ami-0873b46c45c11058d
    sa-east-1:
      AMALINUX: ami-018ccfb6b4745882a
    eu-west-1:
      AMALINUX: ami-07d9160fa81ccffb5
    eu-west-2:
      AMALINUX: ami-0a13d44dccf1f5cf6
    eu-west-3:
      AMALINUX: ami-093fa4c538885becf
    eu-central-1:
      AMALINUX: ami-0c115dbd34c69a004
    ap-southeast-1:
      AMALINUX: ami-0cd31be676780afa7
    ap-southeast-2:
      AMALINUX: ami-0ded330691a314693
    ap-northeast-1:
      AMALINUX: ami-0cc75a8978fbbc969
    ap-northeast-2:
      AMALINUX: ami-0bd7691bf6470fe9c
    ap-south-1:
      AMALINUX: ami-0ebc1ac48dfd14136
    ca-central-1:
      AMALINUX: ami-013d1df4bcea6ba95

  InstanceSize:
    SMALL:
      "EC2" : "t2.micro"
      "DB" : "db.t2.micro"
    MEDIUM:
      "EC2" : "t2.small"
      "DB" : "db.t2.small"
    LARGE:
      "EC2" : "t2.medium"
      "DB" : "db.t2.medium"
Resources:
  DB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass: !FindInMap [InstanceSize, !Ref EnvironmentSize, DB] # Dynamic mapping + Pseudo Parameter
      DBName: !Ref DatabaseName
      Engine: MySQL
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX] # Dynamic mapping + Pseudo Parameter
      InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2]
      KeyName: AdvancedCFN
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum install httpd php mysql php-mysql -y
            yum update -y
            chkconfig httpd on
            service httpd start
            cd /var/www/html
            wget https://wordpress.org/wordpress-5.1.1.tar.gz
            tar -zxvf wordpress-5.1.1.tar.gz --strip 1
            rm wordpress-5.1.1.tar.gz
            cp wp-config-sample.php wp-config.php
            sed -i 's/database_name_here/${DatabaseName}/g' wp-config.php
            sed -i 's/localhost/${DB.Endpoint.Address}/g' wp-config.php
            sed -i 's/username_here/${DatabaseUser}/g' wp-config.php
            sed -i 's/password_here/${DatabasePassword}/g' wp-config.php
  S3:
    Type: "AWS::S3::Bucket"
